version: "3.9"
services:
  db:
    image: postgres:16
    container_name: pockito-postgres
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pockito}
      POSTGRES_USER: ${POSTGRES_USER:-pockito}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pockito}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: pockito-keycloak
    command: ["start-dev", "--http-port=8081"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    ports: ["8081:8081"]
    depends_on:
      db:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  pgdata: {}
